### ISSUE TITLE
ilproj's cannot be built outside of Windows

### ISSUE THREAD

**Issue by mellinoe** [dotnet/buildtools#1301]
We need to start restoring the [ilasm](https://www.nuget.org/packages/Microsoft.NETCore.ILAsm/) package for the correct RID (during init-tools), and then hook that path up into ilproj.targets.

**Comment by alexperovich** [comment]
A while back I tried to do this and the ilasm from the package was not working correctly. I will see if I can dig up the branch I had.

**Comment by mellinoe** [comment]
I remember having a similar issue, but it was so long ago that I'm hoping everything is fixed by now.

**Comment by alexperovich** [comment]
Well the package has a new version and my branch doesn't have any conflicts. I'll rebase and see if it works.

**Comment by alexperovich** [comment]
Yep, the issue still happens. The signing step fails with the following error:

> E:\corefx\Tools\sign.targets(70,5): error : E:\corefx\bin/obj/AnyOS.AnyCPU.Debug/System.Reflection.TestModule/System.Reflection.TestModule.dll: PE file is not a delay-signed assembly. [E:\corefx\src\System.Runtime\tests\TestModule\System.Reflection.TestModule.ilproj]

And an analysis of the produced binary in ildasm reports the wrong metadata version on the assembly.
Inbox ilasm produces version: `v4.0.30319` and the package version produces `v4.0.22220`

**Comment by weshaggard** [comment]
If it is just a signing issue we can disable signing for this test binary.

**Comment by alexperovich** [comment]
I don't think the binary would work unless the runtime supports loading PE files with a different metadata version.

**Comment by mellinoe** [comment]
So is this a bug in the .NET Core version of idasm?

**Comment by alexperovich** [comment]
Yes.

**Comment by ericstj** [comment]
@mellinoe you mentioned that this should work now.  When you bring over ilasm can you undo the workaround here: https://github.com/dotnet/corefx/blob/fbafeb42ea7488fa62240f03a233ddef9382a210/src/System.Runtime.CompilerServices.Unsafe/src/include/netstandard/coreassembly.h#L10-L20  and see if coreclr ilasm is broken in the same way desktop was?  If so we need to open a coreclr bug.

**Comment by mellinoe** [comment]
This has been fixed.
